### ISSUE TITLE
[ENHANCE] Add All NEAR Wallets to Wallet Selector

### ISSUE THREAD

**Issue by codingshot** [PotLock/next-app-old#47] opened 2024-01-18 07:34 UTC
# Summary
Add all wallets on wallet selector  https://github.com/near/wallet-selector/tree/main
# Motivation
- want collaboration with all products and wallets in ecosystem
# Description

- [x] add mintbase wallet
- [x] here wallet
- [x] nightly wallet
- [x] meteor wallet 
- [x] my near mobile wallet
- [x] welldone wallet
- [x] coin98 wallet
- [x] ramper wallet

**Comment by lachlanglen** [comment] 2024-01-30 15:27
Duplicate of https://github.com/orgs/PotLock/projects/2/views/2?pane=issue&itemId=50221578

**Closed as completed by lachlanglen** 2024-01-30 15:27 UTC
Labels: enhancement
